application: umg-web
version: 1
runtime: java
public_root: /app/static
sessions_enabled: true
threadsafe: true

resource_files:
  - include: /**/*
  - exclude: README.md 
  - exclude: package.json 
  - exclude: manifest.json


handlers:
  - url: /*
    servlet: org.ringojs.jsgi.JsgiServlet
    name: ringo
    init_params:  
        module-path: WEB-INF/app
        config: main
        app: app 
        optlevel: -1
        ringo-home: /WEB-INF